// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTUj4foVrONHquTqjET3_wMAxnmTuIZZc',
    appId: '1:779738266084:web:bb38b8ccb9f2338f71aff1',
    messagingSenderId: '779738266084',
    projectId: 'firestoredemo-d85ce',
    authDomain: 'firestoredemo-d85ce.firebaseapp.com',
    storageBucket: 'firestoredemo-d85ce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8G8FR5qWL0_kyIPlngi4Z6myDWlATpk4',
    appId: '1:779738266084:android:46bbe860f223892e71aff1',
    messagingSenderId: '779738266084',
    projectId: 'firestoredemo-d85ce',
    storageBucket: 'firestoredemo-d85ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2avoyrPLgdXaH4GLZR7OCVZ7bvQN4faw',
    appId: '1:779738266084:ios:dbbb2c48f3cd923671aff1',
    messagingSenderId: '779738266084',
    projectId: 'firestoredemo-d85ce',
    storageBucket: 'firestoredemo-d85ce.firebasestorage.app',
    iosBundleId: 'com.example.firebaseFirestore',
  );
}
